### ISSUE TITLE
VBS runtime error on existing function FIX

### ISSUE THREAD

**Issue by nitrocode** [miyamiya/VBSdoc#1]
Hi,

I had a function with the exact same name and parameters as another function and when I ran your script, it would fail when it found the duplicate function. 

I replaced line 611:

```
            methods.Add .Item(7), d
```

and replaced it with:

```
            if ( methods.exists( .Item(7) ) ) Then
                log.LogDebug "> Found duplicate " & .Item(7)
            Else
                methods.Add .Item(7), d
            End If
```

Hope this helps anyone else who is using your script!

**Comment by miyamiya** [comment]
Oh. sorry...
I was careless and did not notice issue. :cold_sweat:
and thankful to you!!   :smiley:

I check, please give me time. :sweat_smile:

**Comment by miyamiya** [comment]
I bought Windows Machine!

Thank you very much for your pull request! :+1:

**Comment by nitrocode** [comment]
Anytime! Thanks for merging the change. :)
